### ISSUE TITLE
Groups are not draggable sideways in IE11

### ISSUE THREAD

**Issue by martinbdz** [jillix/svg.draggy.js#17]
Normal elements (like a rect) can be dragged without problems in IE11 but it is not working correctly for groups. I am only able to drag the group up and down.

**Comment by IonicaBizau** [comment]
Ouch... Does IE11 still exist? :smile:

Contributions are more than welcome! :sparkles: I'm not using Windows...

**Comment by IonicaBizau** [comment]
And of course, should you have any questions, let me know. :four_leaf_clover:

**Comment by martinbdz** [comment]
Sometimes it is still a requirement ;)
It wasn't a problem with draggy but with svg.js itself. The following pull request solved the issue:
https://github.com/wout/svg.js/pull/372

**Comment by IonicaBizau** [comment]
Oh, glad to hear! :smile_cat:
