### ISSUE TITLE
hope comming version will have custom drag action

### ISSUE THREAD

**Issue by CyrusNG** [jillix/svg.draggy.js#19]
May I know whether comming version will have custom drag action that I can handle graphic in "dragmove" event function instead of svg.draggy.js?

**Comment by IonicaBizau** [comment]
This is already implemented: https://github.com/jillix/svg.draggy.js#dragmove

The `dragmove` event is emitted when dragging the element.

**Comment by CyrusNG** [comment]
Sorry for my unclear description.
Actually, I wanna one feature that is without any drag effect, and set custom effect like changing svg's path instead of moving the whole svg's path in dragmove function.

**Comment by IonicaBizau** [comment]
@CyrusNG I'm not sure, but maybe this [`animate`](https://github.com/wout/svg.js#animate) function is what you want?

**Comment by Fuzzyma** [comment]
@CyrusNG this is implemented in the official [draggable plugin](https://github.com/svgdotjs/svg.draggable.js) from svg.js.
You can cancel the default dragmove and do anything else instead.
