### ISSUE TITLE
When dragging image we get undefined start event

### ISSUE THREAD

**Issue by slavede** [jillix/svg.draggy.js#20]
But this only happens if image is embeded in group
![image](https://user-images.githubusercontent.com/2838038/37276810-275843cc-25e3-11e8-9955-ec41b7c96e22.png)

**Comment by slavede** [comment]
Invalid

**Comment by 13djwright** [comment]
Interesting that you closed this issue. I can make it happen on the example website.
If you are dragging, and then right click, the error occurs consistently.
It seems like that variable is never actually used. I haven't had any issues with removing that bit of code.
What do you think?

**Comment by slavede** [comment]
To be honest, I can't remember why I closed it as invalid. Probably I should have put more details. But probably it was a random behaviour.
