### ISSUE TITLE
CTM not considered

### ISSUE THREAD

**Issue by ctzurcanu** [jillix/svg.draggy.js#4]
This is a problem that persists from the original svg.draggable
the dx dy displacement should take into consideration the Current Transformation Matrix of the target

**Comment by IonicaBizau** [comment]
Do you have any example to reproduce the issue?

**Comment by ctzurcanu** [comment]
No. Not online. But I can explain what the problem is: svg.js does not keep track of what external libraries do with the SVG elements. Any change to a transform of any of the element's container will cause it to not move as expected. Therefore getCTM has to be used. Then the matrix applied to dx and dy.

**Comment by IonicaBizau** [comment]
From what I understand after fixing this, [this function](https://github.com/jillix/svg.draggable.js/blob/c242312adf318b1c91e875085079e5907609bf52/svg.draggable.js#L74-L84) will be obsolete, right?

Is this issue about getting the global matrix?

**Comment by ctzurcanu** [comment]
I am not sure about that function. But it is about the global matrix for the target element(s), yes.

**Comment by IonicaBizau** [comment]
The mad science from that function is to get the global zoom.

This is not a priority for us, but if you make a PR with this improvement, we would be happy to review it and merge it in the master branch. :smile:

**Comment by ctzurcanu** [comment]
PR being..? But don't worry, if you won't fix, I will fix it myself for my app.

**Comment by ctzurcanu** [comment]
ok. I think it is Pull Request. Fine.

**Comment by IonicaBizau** [comment]
Pull request.

> I will fix it myself for my app.

Fix it in your local `svg.draggable.js` file and then make a pull request.  :smile:

**Comment by ctzurcanu** [comment]
Actually.. This my be a harder problem than I bargained for:
Suppose that the element has a path like doc>g1>g2>g3>el. If a svg.js transfom lives in each g1 and g3 and an external lib changes just g2, calculating CTM*dx or dy will not give you the move coords for el. You would have to know the CTM for each container on the path to apply the inverse of each to dx, dy.. So this lib may not be the most efficient point to apply a solution. I will return to this if I change my mind :D

**Comment by ctzurcanu** [comment]
Solution: force the external lib to update the svg.js transform on g2

**Comment by Fuzzyma** [comment]
@ctzurcanu consider taking a look at the [svg.draggable.js](https://github.com/svgdotjs/svg.draggable.js) plugin again which does consider every transformation with the help of `screenCTM`
