### ISSUE TITLE
dragstart, dragmove and dragend - no delta in callback

### ISSUE THREAD

**Issue by loredanacirstea** [jillix/svg.draggy.js#5]
The dragstart, dragmove and dragend callbacks do not give the delta variable - only the event. If I do:

```
rect.on("dragmove", function(delta, event) {
   console.log(delta);
    console.log(event);
});
```

`delta` will be the actual `event` and `event` is `undefined`

I wanted to do a jsfiddle: http://jsfiddle.net/loredana_cirstea/L2sjjc3b/1/ , but I do not know of a cdn link to your library. I tried a link to the raw file, but of course, it has a 'text/plain' mime type.

**Comment by IonicaBizau** [comment]
Thanks for the report. I reproduced it here: http://jsfiddle.net/L2sjjc3b/3/

This line should be fixed: https://github.com/jillix/svg.draggable.js/blob/c242312adf318b1c91e875085079e5907609bf52/svg.draggable.js#L145

**Comment by loredanacirstea** [comment]
Ok, thank you :)

**Comment by IonicaBizau** [comment]
If you liked to fix it, I would be glad to review and merge a pull request with this fix. :smile:

**Comment by loredanacirstea** [comment]
It may actually be an svgjs issue with custom events: https://github.com/wout/svg.js/pull/319 . So, I will close this for now. Anyway, as a temporary solution I just get the initial coordinates with on `dragstart` and use them on `dragmove` .

**Comment by IonicaBizau** [comment]
This indeed needs to be fixed in this library. Probably the use of `CustomEvent` is wrong.

**Comment by IonicaBizau** [comment]
I updated the JSFiddle, after merging #6: http://jsfiddle.net/L2sjjc3b/4/

**Comment by Fuzzyma** [comment]
The CustomEvents are fixed with the latest commit (Fuzzyma/svg.js@4b2e055187f2f33d14f9e7573ce34b9333b553a3)

Note that the data passed to the event is accessible via `e.detail.key`

**Comment by IonicaBizau** [comment]
@Fuzzyma Passing the detail object is exactly what I did in #6. See [these lines](https://github.com/jillix/svg.draggable.js/pull/6/files#diff-41c9c10a255c3e3e15a9c8e9790c78d4L63). Are there any fixes we have to commit here after the change from the svg.js library?

**Comment by Fuzzyma** [comment]
Well you could now use element.fire('name', data) but you don't have to
