### ISSUE TITLE
Error with callback functios

### ISSUE THREAD

**Issue by ccvca** [jillix/svg.draggy.js#7]
https://github.com/jillix/svg.draggable.js/blob/master/svg.draggable.js#L120

The 'else' in this line must be deleted. Otherwise the y-Value will be always the same.
There it is right: https://github.com/wout/svg.draggable.js/blob/master/svg.draggable.js#L97

**Comment by IonicaBizau** [comment]
Good catch! Could you please create a pull request?

**Comment by IonicaBizau** [comment]
:ship: `1.0.0`
